<div>
    {% if not is_index %}
        <div style="text-align:center;color: #ccc;font-size:14px;">
            ------------------------------ 
			<i class="fa fa-copyright"> 版权声明： <a style="font-family:Microsoft YaHei;color:#9D9D9D;border-bottom:none;" href="https://ttfisher.github.io/" title="Lin.C的个人主页">本博客</a> 所有文章除特别声明外，均由 <a style="font-family:Microsoft YaHei;color:#9D9D9D;border-bottom:none;" href="https://ttfisher.github.io/" title="Lin.C的个人主页">Lin.C</a> 创作，如需转载请注明出处，谢谢！</i>
			------------------------------
        </div>
    {% endif %}
</div>